; Authored LLVM/AIR-style fixture. NOT generated by Apple's Metal compiler.
; Exercises the translator and its descriptor ABI without requiring a Mac.
%Params = type { i32, i32 }
define void @vector_add(ptr addrspace(1) %a, ptr addrspace(1) %b, ptr addrspace(1) %out, ptr addrspace(1) %params, <3 x i32> %gid) {
entry:
  %i = extractelement <3 x i32> %gid, i32 0
  %count_ptr = getelementptr %Params, ptr addrspace(1) %params, i64 0, i32 0
  %count = load i32, ptr addrspace(1) %count_ptr, align 4
  %within = icmp ult i32 %i, %count
  br i1 %within, label %work, label %done
work:
  %offset_ptr = getelementptr %Params, ptr addrspace(1) %params, i64 0, i32 1
  %offset = load i32, ptr addrspace(1) %offset_ptr, align 4
  %j = add i32 %i, %offset
  %index = zext i32 %j to i64
  %ap = getelementptr i32, ptr addrspace(1) %a, i64 %index
  %bp = getelementptr i32, ptr addrspace(1) %b, i64 %index
  %op = getelementptr i32, ptr addrspace(1) %out, i64 %index
  %av = load i32, ptr addrspace(1) %ap, align 4
  %bv = load i32, ptr addrspace(1) %bp, align 4
  %sum = add i32 %av, %bv
  store i32 %sum, ptr addrspace(1) %op, align 4
  br label %done
done:
  ret void
}
!air.kernel = !{!0}
!0 = !{ptr @vector_add, !1, !2}
!1 = !{}
!2 = !{!3, !4, !5, !6, !7}
!3 = !{i32 0, !"air.buffer", !"air.location_index", i32 0, i32 1, !"air.read", !"air.address_space", i32 1, !"air.arg_type_name", !"uint", !"air.arg_name", !"a"}
!4 = !{i32 1, !"air.buffer", !"air.location_index", i32 1, i32 1, !"air.read", !"air.address_space", i32 1, !"air.arg_type_name", !"uint", !"air.arg_name", !"b"}
!5 = !{i32 2, !"air.buffer", !"air.location_index", i32 2, i32 1, !"air.write", !"air.address_space", i32 1, !"air.arg_type_name", !"uint", !"air.arg_name", !"result"}
!6 = !{i32 3, !"air.buffer", !"air.buffer_size", i32 8, !"air.location_index", i32 3, i32 1, !"air.read", !"air.address_space", i32 1, !"air.arg_type_size", i32 8, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"Params", !"air.arg_name", !"params"}
!7 = !{i32 4, !"air.thread_position_in_grid", !"air.arg_type_name", !"uint3", !"air.arg_name", !"gid"}
